NAME = libft.a

CC = cc
CFLAGS = -Wall -Werror -Wextra
SRC = ft_isalnum.c  ft_isprint.c  ft_memmove.c  ft_strlcat.c   ft_strnstr.c  libft.h \
ft_atoi.c    ft_isalpha.c  ft_memchr.c   ft_memset.c   ft_strlcopy.c  ft_strrchr.c  \
ft_bzero.c   ft_isascii.c  ft_memcmp.c   ft_stardup.c  ft_strlen.c    ft_tolower.c \
ft_calloc.c  ft_isdigit.c  ft_memcpy.c   ft_strchr.c   ft_strncpy.c   ft_toupper.c \



